# Generated by Django 2.2 on 2020-10-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
